name: 'GitHub Actions'

on:
  push:
    branches: 
      - main
  schedule:
   - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  ddy:
    runs-on: ubuntu-latest
    steps:
      - name: Set time zone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: 'Set up Python'
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.8

      - name: 'Install dependencies'
        run: python -m pip install --upgrade pip

      - name: 'Install requirements'
        run: pip install -r ./requirements.txt

      - name: 'Working'
        run: |
          mv *.csv oldcsv/
          wget -O IPDBproxy.txt  https://raw.githubusercontent.com/ymyuuu/IPDB/main/proxy.txt
          cp raw_ip.txt ip.txt 
          cat IPDBproxy.txt >> ip.txt 
          mv IPDBproxy.txt oldrealip/IPDBproxy-$(date +%Y%m%d%H%M%S).txt
          chmod +x ./iptest.sh
          bash ./iptest.sh -t 100
          python ./df_sorted.py
          python ./create_proxyip.py
          mv realip*.txt oldrealip/
          rm -rf ip.txt

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "⌚️$(date +%Y%m%d%H%M%S)" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
